server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30
      
spring:
  datasource:
      url: jdbc:oracle:thin:@192.168.0.50:1521/PDSYS
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: pd_insa
      password: pd_insa

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi: 
      enabled: always
